# Generated by Django 4.1.6 on 2023-07-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='realtor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='specific_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
