# Generated by Django 4.2.3 on 2023-09-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land', '0003_rename_ward_land_name_land_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='ward',
            field=models.TextField(blank=True, null=True),
        ),
    ]
